server:
 port: 10001

spring:
 application:
   name: api-gate
# 数据库访问配置
# 主数据源，默认的
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sms?useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password:
  #使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource


#该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.iblogstreet.apigate.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印日志
    cache-enabled: true   # 使全局的映射器启用或禁用缓存
    lazy-loading-enabled: true   #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    aggressive-lazy-loading: true  #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
    multiple-result-sets-enabled: true #是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    useColumnLabel: true #是否可以使用列的别名 (取决于驱动的兼容性) default:true
    use-generated-keys: true #允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    auto-mapping-behavior: PARTIAL #指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    defaultExecutorType: simple #这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    mapUnderscoreToCamelCase: true #使用驼峰命名法转换字段
    localCacheScope: session #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    jdbc-type-for-null: null #设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型

